### ISSUE TITLE
Broken disaplay of Favorites after update to 2024-06

### ISSUE THREAD

**Issue by aztechowski** [fidley/ABAPFavorites#96]
After updating to latest Eclipse, it seems that the plugin does not work as intended. The only column which is displayed is the LinkedTo column. There is following error in the log, but it doesn't seems to be linked with Favorites plugin (at least not directly).

```
java.lang.NullPointerException: Cannot invoke "com.codeaffine.eclipse.swt.widget.scrollable.context.Reconciliation.runWithSuspendedBoundsReconciliation(java.lang.Runnable)" because "this.reconciliation" is null
	at com.codeaffine.eclipse.swt.widget.scrollable.TreeAdapter.setBounds(TreeAdapter.java:311)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:697)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:201)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1339)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1740)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4789)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5050)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:91)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5656)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4802)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5050)
	at org.eclipse.swt.internal.win32.OS.EndDeferWindowPos(Native Method)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:997)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:974)
	at org.eclipse.swt.widgets.Composite.setResizeChildren(Composite.java:1170)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1744)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4789)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5050)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:91)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5656)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4802)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5050)
	at org.eclipse.swt.internal.win32.OS.EndDeferWindowPos(Native Method)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:997)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:974)
	at org.eclipse.swt.widgets.Composite.setResizeChildren(Composite.java:1170)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1340)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1345)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1345)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1345)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1345)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1345)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1345)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1345)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1345)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1345)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1324)
	at org.eclipse.swt.widgets.Composite.setLayoutDeferred(Composite.java:1131)
	at org.eclipse.swt.widgets.Display.runDeferredLayouts(Display.java:4107)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3666)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
```

**Comment by fidley** [comment]
Strange, works for me. 
![image](https://github.com/fidley/ABAPFavorites/assets/7912195/355bc7ba-0a4b-4665-9ceb-750d72b0c5a2)
I guess you have latest version of plugin?

**Comment by aztechowski** [comment]
Ha! You reply helped me to find out solution. I don't know why, but the name column, after update to 2024-06, became very thinny (1-2 pixels). I just grabbed the bar and moved LinkedTo the column to the right.... and voila! 
P.S. Yes, I've the latest version.
